sudo: required

language: ruby

services:
  - docker

rvm:
  - 2.4

script: bundle exec rspec spec

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dpca/slack-channel-exporter .;
    docker push dpca/slack-channel-exporter;
    fi
